steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/itomise-blog/frontend', '-f', 'frontend/Dockerfile', 'frontend']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/itomise-blog/frontend']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'frontend', 
    '--image', 'gcr.io/itomise-blog/frontend', 
    '--region', 'us-central1',
    '--platform', 'managed',
    '--allow-unauthenticated'
  ]
images:
- gcr.io/itomise-blog/frontend
