version: '2.0'
services:
  local-db:
    image: postgres:latest
    container_name: local-db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: local
    ports:
      - 15432:5432
    volumes:
      - ./db/local/data:/var/lib/postgresql/data
      - ./db/local/init:/docker-entrypoint-initdb.d
