name: Run Backend Tests

on:
  push:
    paths:
      - 'backend/**'

jobs:
  call_all_tests:
    uses: ./.github/workflows/backend_test_app.yaml
    with:
      project_name: :adapters:blogApi
    strategy:
      fail-fast: false
      matrix:
        project_name:
          - :adapters:adminApi
          - :adapters:blogApi
          - :core
    with:
      project_name: ${{ matrix.project_name }}