name: Run Backend Tests

on:
  push:
    paths:
      - 'backend/**'

jobs:
  call_all_tests:
    uses: ./.github/workflows/backend_test_app.yaml
    strategy:
      fail-fast: false
      matrix:
        project_name:
          - :adapters:adminApi
          - :adapters:blogApi
          - :adapters:blogDb
          - :core
    with:
      project_name: ${{ matrix.project_name }}
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      DB_USER: ${{ secrets.DB_USER }}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}
      JWT_ENCRYPTION_KEY: ${{ secrets.JWT_ENCRYPTION_KEY }}
      JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
      REDIS_ENDPOINT: ${{ secrets.REDIS_ENDPOINT }}
      SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
      SESSION_SIGN_KEY: ${{ secrets.SESSION_SIGN_KEY }}