name: Run Backend Tests

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run PostgreSQL
        run: docker-compose -f docker-compose.yml up -d test-db

      - name: Run Redis
        run: docker-compose -f docker-compose.yml up -d test-redis

      - name: Run Backend Tests
        run: SESSION_SIGN_KEY=${{ env.SESSION_SIGN_KEY }} ./gradlew :admin:test --stacktrace
        env:
          DB_PASSWORD: ${{ env.DB_PASSWORD }}
          DB_URL: ${{ env.DB_URL }}
          DB_USER: ${{ env.DB_USER }}
          GOOGLE_OAUTH2_CLIENT_SECRET: ${{ env.GOOGLE_OAUTH2_CLIENT_SECRET }}
          JWT_ENCRYPTION_KEY: ${{ env.JWT_ENCRYPTION_KEY }}
          JWT_PRIVATE_KEY: ${{ env.JWT_PRIVATE_KEY }}
          REDIS_ENDPOINT: ${{ env.REDIS_ENDPOINT }}
          SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}
          SESSION_SIGN_KEY: ${{ env.SESSION_SIGN_KEY }}

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'